DROP TABLE MAGAZIE;
DROP TABLE VANZARI;
DROP TABLE PRODUSE;
DROP TABLE STARE_PRODUS;
DROP TABLE NUME_PRODUCATOR;
DROP TABLE TIP_PRODUS;
DROP SEQUENCE NUME_PRODUCATOR_ID_FIRMA_SEQ;
DROP SEQUENCE PRODUSE_ID_P_CR_SEQ;
DROP SEQUENCE STARE_PRODUS_ID_STARE_SEQ;
DROP SEQUENCE TIP_PRODUS_ID_PRODUS_SEQ;
--De completat cu pachete si triggere
