EXECUTE nume_producator_pkg.inserare_producator('Intel');
EXECUTE nume_producator_pkg.inserare_producator('Samsung');
EXECUTE nume_producator_pkg.inserare_producator('Qualcomm');
EXECUTE nume_producator_pkg.inserare_producator('Texas Instruments');
EXECUTE nume_producator_pkg.inserare_producator('CapXon');
EXECUTE stare_produs_pkg.inserare_stare('Nou');
EXECUTE stare_produs_pkg.inserare_stare('Zgariat');
EXECUTE stare_produs_pkg.inserare_stare('Folosit');
EXECUTE stare_produs_pkg.inserare_stare('Defect');
EXECUTE stare_produs_pkg.inserare_stare('Expirat');
EXECUTE tip_produs_pkg.inserare_tip_produs('Condensator');
EXECUTE tip_produs_pkg.inserare_tip_produs('Bobina');
EXECUTE tip_produs_pkg.inserare_tip_produs('TranzistorBJ');
EXECUTE tip_produs_pkg.inserare_tip_produs('TranzistorMOS');
EXECUTE tip_produs_pkg.inserare_tip_produs('Rezistenta');
EXECUTE tip_produs_pkg.inserare_tip_produs('Dioda');
EXECUTE produse_pkg.inserare_produs('Condensator','Capacitate','CapXon','Nou');
EXECUTE produse_pkg.inserare_produs('TranzistorMOS','VDS','Intel','Folosit');
EXECUTE produse_pkg.inserare_produs('Bobina','Inductanta','Samsung','Zgariat');
EXECUTE produse_pkg.inserare_produs('Rezistenta','Rezistenta','Texas Instruments','Defect');
EXECUTE produse_pkg.inserare_produs('Dioda','Va','Qualcomm','Expirat');
EXECUTE produse_pkg.inserare_produs('Condensator','Capacitate','Intel','Nou');
EXECUTE magazie_pkg.insert_magazie('Condensator','Capacitate','CapXon','Nou',200,40);
EXECUTE magazie_pkg.insert_magazie('TranzistorMOS','VDS','Intel','Folosit',10,50);
EXECUTE magazie_pkg.insert_magazie('Bobina','Inductanta','Samsung','Zgariat',45,50);
EXECUTE magazie_pkg.insert_magazie('Rezistenta','Rezistenta','Texas Instruments','Defect',60,10);
EXECUTE magazie_pkg.insert_magazie('Dioda','Va','Qualcomm','Expirat',30,60);
EXECUTE vanzari_pkg.inserare_vanzare('Condensator','Capacitate','CapXon','Nou',100,'04-APR-22');
EXECUTE vanzari_pkg.inserare_vanzare('TranzistorMOS','VDS','Intel','Folosit',1,'03-APR-22');
EXECUTE vanzari_pkg.inserare_vanzare('Bobina','Inductanta','Samsung','Zgariat',10,'05-APR-22');
EXECUTE vanzari_pkg.inserare_vanzare('Rezistenta','Rezistenta','Texas Instruments','Defect',25,'07-APR-22');
EXECUTE vanzari_pkg.inserare_vanzare('Dioda','Va','Qualcomm','Expirat',20,'08-APR-22');