EXECUTE nume_producator_pkg.inserare_producator('Intel');
EXECUTE nume_producator_pkg.inserare_producator('Samsung');
EXECUTE nume_producator_pkg.inserare_producator('Qualcomm');
EXECUTE nume_producator_pkg.inserare_producator('Texas Instruments');
EXECUTE nume_producator_pkg.inserare_producator('CapXon');
EXECUTE stare_produs_pkg.inserare_stare('Nou');
EXECUTE stare_produs_pkg.inserare_stare('Zgariat');
EXECUTE stare_produs_pkg.inserare_stare('Folosit');
EXECUTE stare_produs_pkg.inserare_stare('Defect');
EXECUTE stare_produs_pkg.inserare_stare('Expirat');
EXECUTE tip_produs_pkg.inserare_tip_produs('Condensator');
EXECUTE tip_produs_pkg.inserare_tip_produs('Bobina');
EXECUTE tip_produs_pkg.inserare_tip_produs('TranzistorBJ');
EXECUTE tip_produs_pkg.inserare_tip_produs('TranzistorMOS');
EXECUTE tip_produs_pkg.inserare_tip_produs('Rezistenta');
EXECUTE tip_produs_pkg.inserare_tip_produs('Dioda');
EXECUTE produse_pkg.inserare_produs('Condensator','Capacitate','CapXon','Nou');
EXECUTE produse_pkg.inserare_produs('TranzistorMOS','VDS','Intel','Folosit');
EXECUTE produse_pkg.inserare_produs('Bobina','Inductanta','Samsung','Zgariat');
EXECUTE produse_pkg.inserare_produs('Rezistenta','Rezistenta','Texas Instruments','Defect');
EXECUTE produse_pkg.inserare_produs('Dioda','Va','Qualcomm','Expirat');
EXECUTE produse_pkg.inserare_produs('Condensator','Capacitate','Intel','Nou');
EXECUTE produse_pkg.stergere_produs('Condensator','Capacitate','CapXon','Nou');--De adaugat trigger pentru a verifica unicitatea
